<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AclActions
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclActions extends EntityRepository
{
}