<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AclGroupsPermissions
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclGroupsPermissions extends EntityRepository
{
}