<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AclResources
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclResources extends EntityRepository
{
}