<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AclUsersPermissions
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclUsersPermissions extends EntityRepository
{
}