<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnterprisesProfiles
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnterprisesProfiles extends EntityRepository
{
}