<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnterprisesClients
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnterprisesClients extends EntityRepository
{
}