<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnterprisesModules
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnterprisesModules extends EntityRepository
{
}