<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnterprisesAccountingYear
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnterprisesAccountingYear extends EntityRepository
{
}