<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnterprisesBankStatements
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnterprisesBankStatements extends EntityRepository
{
}