<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Enterprises
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Enterprises extends EntityRepository
{
}