<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntreprisesIncomes
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreprisesIncomes extends EntityRepository
{
}