<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Modules
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Modules extends EntityRepository
{
}