<?php

namespace Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Sessions
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sessions extends EntityRepository
{
}