<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesAclUsersPermissionsProxy extends \Entities\AclUsersPermissions implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setAccessType($accessType)
    {
        $this->_load();
        return parent::setAccessType($accessType);
    }

    public function getAccessType()
    {
        $this->_load();
        return parent::getAccessType();
    }

    public function setCreatedOn($createdOn)
    {
        $this->_load();
        return parent::setCreatedOn($createdOn);
    }

    public function getCreatedOn()
    {
        $this->_load();
        return parent::getCreatedOn();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setAclAction(\Entities\AclActions $aclAction)
    {
        $this->_load();
        return parent::setAclAction($aclAction);
    }

    public function getAclAction()
    {
        $this->_load();
        return parent::getAclAction();
    }

    public function setUser(\Entities\Users $user)
    {
        $this->_load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->_load();
        return parent::getUser();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'accessType', 'createdOn', 'id', 'acl_action', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}