<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesAclActionsProxy extends \Entities\AclActions implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setActionIdentifer($actionIdentifer)
    {
        $this->_load();
        return parent::setActionIdentifer($actionIdentifer);
    }

    public function getActionIdentifer()
    {
        $this->_load();
        return parent::getActionIdentifer();
    }

    public function setActionDescription($actionDescription)
    {
        $this->_load();
        return parent::setActionDescription($actionDescription);
    }

    public function getActionDescription()
    {
        $this->_load();
        return parent::getActionDescription();
    }

    public function setRoleOrder($roleOrder)
    {
        $this->_load();
        return parent::setRoleOrder($roleOrder);
    }

    public function getRoleOrder()
    {
        $this->_load();
        return parent::getRoleOrder();
    }

    public function setCreatedOn($createdOn)
    {
        $this->_load();
        return parent::setCreatedOn($createdOn);
    }

    public function getCreatedOn()
    {
        $this->_load();
        return parent::getCreatedOn();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function addAclUserPermission(\Entities\AclUsersPermissions $aclUserPermission)
    {
        $this->_load();
        return parent::addAclUserPermission($aclUserPermission);
    }

    public function getAclUserPermission()
    {
        $this->_load();
        return parent::getAclUserPermission();
    }

    public function setResources(\Entities\AclResources $resources)
    {
        $this->_load();
        return parent::setResources($resources);
    }

    public function getResources()
    {
        $this->_load();
        return parent::getResources();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'actionIdentifer', 'actionDescription', 'role_order', 'createdOn', 'id', 'acl_user_permission', 'resources');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}