<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesEnterprisesProfilesProxy extends \Entities\EnterprisesProfiles implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setTurnOver($turnOver)
    {
        $this->_load();
        return parent::setTurnOver($turnOver);
    }

    public function getTurnOver()
    {
        $this->_load();
        return parent::getTurnOver();
    }

    public function setSiret($siret)
    {
        $this->_load();
        return parent::setSiret($siret);
    }

    public function getSiret()
    {
        $this->_load();
        return parent::getSiret();
    }

    public function setIsTva($isTva)
    {
        $this->_load();
        return parent::setIsTva($isTva);
    }

    public function getIsTva()
    {
        $this->_load();
        return parent::getIsTva();
    }

    public function setTva($tva)
    {
        $this->_load();
        return parent::setTva($tva);
    }

    public function getTva()
    {
        $this->_load();
        return parent::getTva();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setDescription($description)
    {
        $this->_load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->_load();
        return parent::getDescription();
    }

    public function setHomePage($homePage)
    {
        $this->_load();
        return parent::setHomePage($homePage);
    }

    public function getHomePage()
    {
        $this->_load();
        return parent::getHomePage();
    }

    public function setLogoPath($logoPath)
    {
        $this->_load();
        return parent::setLogoPath($logoPath);
    }

    public function getLogoPath()
    {
        $this->_load();
        return parent::getLogoPath();
    }

    public function setCity($city)
    {
        $this->_load();
        return parent::setCity($city);
    }

    public function getCity()
    {
        $this->_load();
        return parent::getCity();
    }

    public function setCountry($country)
    {
        $this->_load();
        return parent::setCountry($country);
    }

    public function getCountry()
    {
        $this->_load();
        return parent::getCountry();
    }

    public function setPhoneNumber($phoneNumber)
    {
        $this->_load();
        return parent::setPhoneNumber($phoneNumber);
    }

    public function getPhoneNumber()
    {
        $this->_load();
        return parent::getPhoneNumber();
    }

    public function setFaxNumber($faxNumber)
    {
        $this->_load();
        return parent::setFaxNumber($faxNumber);
    }

    public function getFaxNumber()
    {
        $this->_load();
        return parent::getFaxNumber();
    }

    public function setUpdatedOn($updatedOn)
    {
        $this->_load();
        return parent::setUpdatedOn($updatedOn);
    }

    public function getUpdatedOn()
    {
        $this->_load();
        return parent::getUpdatedOn();
    }

    public function setCreatedOn($createdOn)
    {
        $this->_load();
        return parent::setCreatedOn($createdOn);
    }

    public function getCreatedOn()
    {
        $this->_load();
        return parent::getCreatedOn();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setEnterpriseProfile(\Entities\Enterprises $enterpriseProfile)
    {
        $this->_load();
        return parent::setEnterpriseProfile($enterpriseProfile);
    }

    public function getEnterpriseProfile()
    {
        $this->_load();
        return parent::getEnterpriseProfile();
    }

    public function setEnterprise(\Entities\Enterprises $enterprise)
    {
        $this->_load();
        return parent::setEnterprise($enterprise);
    }

    public function getEnterprise()
    {
        $this->_load();
        return parent::getEnterprise();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'turnOver', 'siret', 'isTva', 'tva', 'name', 'description', 'homePage', 'logoPath', 'city', 'country', 'phoneNumber', 'faxNumber', 'updatedOn', 'createdOn', 'id', 'enterprise');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}