<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesAclResourcesProxy extends \Entities\AclResources implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setResourceIdentifer($resourceIdentifer)
    {
        $this->_load();
        return parent::setResourceIdentifer($resourceIdentifer);
    }

    public function getResourceIdentifer()
    {
        $this->_load();
        return parent::getResourceIdentifer();
    }

    public function setResourceDescription($resourceDescription)
    {
        $this->_load();
        return parent::setResourceDescription($resourceDescription);
    }

    public function getResourceDescription()
    {
        $this->_load();
        return parent::getResourceDescription();
    }

    public function setResourceType($resourceType)
    {
        $this->_load();
        return parent::setResourceType($resourceType);
    }

    public function getResourceType()
    {
        $this->_load();
        return parent::getResourceType();
    }

    public function setCreatedOn($createdOn)
    {
        $this->_load();
        return parent::setCreatedOn($createdOn);
    }

    public function getCreatedOn()
    {
        $this->_load();
        return parent::getCreatedOn();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function addActions(\Entities\AclActions $actions)
    {
        $this->_load();
        return parent::addActions($actions);
    }

    public function getActions()
    {
        $this->_load();
        return parent::getActions();
    }

    public function setModule(\Entities\Modules $module)
    {
        $this->_load();
        return parent::setModule($module);
    }

    public function getModule()
    {
        $this->_load();
        return parent::getModule();
    }

    public function addGroupPermission(\Entities\AclGroupsPermissions $groupPermission)
    {
        $this->_load();
        return parent::addGroupPermission($groupPermission);
    }

    public function getGroupPermission()
    {
        $this->_load();
        return parent::getGroupPermission();
    }

    public function addEnterprisePermission(\Entities\AclEnterprisesPermissions $enterprisePermission)
    {
        $this->_load();
        return parent::addEnterprisePermission($enterprisePermission);
    }

    public function getEnterprisePermission()
    {
        $this->_load();
        return parent::getEnterprisePermission();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'resourceIdentifer', 'resourceDescription', 'resourceType', 'createdOn', 'id', 'actions', 'group_permission', 'enterprise_permission', 'module');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}