INSERT INTO `modules` (`id`, `name`, `title`, `description`, `version`, `menu`, `enabled`, `type`, `is_core`, `has_settings`, `position`, `home_controller`, `controllers`, `icon_path`, `lang_file_name`) VALUES
(1, 'users', 'a:1:{s:2:"fr";s:24:"Gestion des utilisateurs";}', 'a:1:{s:2:"fr";s:46:"Gérer les utilisateurs et leurs informations.";}', 'v0.1', 'users', 1, 'mod_manager', 1, 0, -38, '0', 'a:1:{i:0;a:1:{s:6:"manage";a:2:{i:0;s:5:"index";i:1;s:3:"add";}}}', 'img/icons/users.png', 'users'),
(34, 'permissions', 'a:1:{s:2:"fr";s:11:"Permissions";}', 'a:1:{s:2:"fr";s:44:"Configurer les permissions des utilisateurs.";}', 'v0.1', '', 1, 'mod_admin', 1, 0, 3, '0', 'a:1:{i:0;a:1:{s:6:"manage";a:5:{i:0;s:5:"index";i:1;s:11:"entreprises";i:2;s:23:"ajax_update_permissions";i:3;s:22:"switch_permission_mode";i:4;s:18:"restore_permission";}}}', 'img/icons/permissions.png', ''),
(41, 'accounting', 'a:1:{s:2:"fr";s:13:"Comptabilité";}', 'a:1:{s:2:"fr";s:35:"Gestion des dépenses, recettes ...";}', 'v0.1', 'accounting', 1, 'mod_entreprise', 1, 0, 0, '0', 'a:4:{i:0;a:1:{s:15:"accounting_year";a:7:{i:0;s:5:"index";i:1;s:3:"add";i:2;s:4:"edit";i:3;s:24:"activate_accounting_year";i:4;s:27:"desactivate_accounting_year";i:5;s:10:"write_mode";i:6;s:9:"read_mode";}}i:1;a:1:{s:7:"analyse";a:1:{i:0;s:5:"index";}}i:2;a:1:{s:15:"bank_statements";a:5:{i:0;s:5:"index";i:1;s:3:"add";i:2;s:6:"upload";i:3;s:6:"import";i:4;s:6:"export";}}i:3;a:1:{s:7:"analyse";a:1:{i:0;s:5:"index";}}}', 'img/icons/accounting.png', 'accounting'),
(30, 'managers', 'a:1:{s:2:"fr";s:20:"Gestion des gérants";}', 'a:1:{s:2:"fr";s:42:"Gérer les gérants et leurs informations.";}', 'v0.2', 'users', 1, 'mod_admin', 1, 0, 2, '0', 'a:1:{i:0;a:1:{s:6:"manage";a:5:{i:0;s:5:"index";i:1;s:5:"users";i:2;s:11:"add_manager";i:3;s:12:"_check_email";i:4;s:15:"_check_username";}}}', 'img/icons/users.png', 'managers'),
(40, 'bank_accounts', 'a:1:{s:2:"fr";s:17:"Comptes bancaires";}', 'a:1:{s:2:"fr";s:46:"Gestion des comptes bancaires de l''entreprise.";}', 'v0.1', 'bank_accounts', 1, 'mod_entreprise', 1, 0, 0, '0', 'a:1:{i:0;a:1:{s:6:"manage";a:3:{i:0;s:5:"index";i:1;s:3:"add";i:2;s:4:"edit";}}}', 'img/icons/bank_accounts.png', 'bank_accounts'),
(29, 'modules', 'a:1:{s:2:"fr";s:24:"Gestionnaire de modules ";}', 'a:1:{s:2:"fr";s:37:"Gestion des  modules et leur contenu.";}', 'v0.3', '', 1, 'mod_admin', 1, 0, 0, '0', 'a:2:{i:0;a:1:{s:6:"manage";a:5:{i:0;s:5:"index";i:1;s:7:"install";i:2;s:6:"update";i:3;s:8:"activate";i:4;s:11:"desactivate";}}i:1;a:1:{s:6:"upload";a:2:{i:0;s:5:"index";i:1;s:14:"upload_process";}}}', 'img/icons/modules.png', 'modules'),
(31, 'settings', 'a:1:{s:2:"fr";s:13:"Configuration";}', 'a:1:{s:2:"fr";s:31:"Configuration de l''application.";}', 'v0.1', '', 1, 'mod_admin', 1, 1, 4, '0', 'a:1:{i:0;a:1:{s:8:"settings";a:0:{}}}', 'img/icons/configuration.png', ''),
(33, 'entreprises', 'a:1:{s:2:"fr";s:22:"Gestion d''entreprises ";}', 'a:1:{s:2:"fr";s:23:"Gérer les entreprises.";}', 'v0.2', 'entreprises', 1, 'mod_admin', 1, 0, 1, '0', 'a:1:{i:0;a:1:{s:6:"manage";a:5:{i:0;s:5:"index";i:1;s:3:"add";i:2;s:6:"assign";i:3;s:4:"edit";i:4;s:11:"ajax_update";}}}', 'img/icons/entreprises.png', 'entreprises');
